---
title: "NBA 2014-2015球季 各隊分析"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##讀取程式碼
```{r echo=TRUE}
#install.packages("SportsAnalytics")
library(SportsAnalytics)
NBA1415<-fetch_NBAPlayerStatistics("14-15")
```

##各隊最辛苦的球員
計算依據為出戰分鐘數最多的球員

```{r echo=TRUE}
WorkHardest<-aggregate(TotalMinutesPlayed ~ Team,NBA1415, max)
NBA1415WorkHardest<-merge(NBA1415,WorkHardest)
output1<-NBA1415WorkHardest[order(NBA1415WorkHardest$TotalMinutesPlayed,decreasing = T)
,c("Team","Name","TotalMinutesPlayed")]
library(knitr)
kable(output1,digit=2)
```

##各隊得分王
計算依據為全季總得分最多的球員

```{r echo=TRUE}
MaxPoint<-aggregate(TotalPoints~Team,NBA1415,max)
#tapply(NBA1415$TotalPoints,NBA1415$Team,max)
NBA1415MaxPoint<-merge(NBA1415,MaxPoint)
output2<-NBA1415MaxPoint[order(NBA1415MaxPoint$TotalPoints,decreasing = T),c("Team","Name","TotalPoints")]
library(knitr)
kable(output2, digits=2)
```

##各隊最有效率的球員
計算依據為全季總得分除以出戰分鐘數的結果最高的球員

```{r echo=TRUE}
x<-c(NBA1415$TotalPoints)
y<-c(NBA1415$TotalMinutesPlayed)
NBA1415$EfficientRate<-x/y
Efficient<-aggregate(EfficientRate~Team,NBA1415,max)
NBA1415Efficient<-merge(NBA1415,Efficient)
output3<-NBA1415Efficient[order(NBA1415Efficient$EfficientRate,decreasing = T)
,c("Team","Name","EfficientRate")]
library(knitr)
kable(output3, digits=2)
```



##測試最有效率的最後一隊WAS 是否真的正確 
列出所有WAS隊的EfficientRate
```{r echo=TRUE}
x<-c(NBA1415$TotalPoints)
y<-c(NBA1415$TotalMinutesPlayed)
NBA1415$EfficientRate<-x/y
Checkcheck<-subset(NBA1415, Team=="WAS")[,c("Team","Name","EfficientRate")]
library(knitr)
kable(Checkcheck, digits=2)
```



##各隊三分球出手最準的球員

```{r echo=TRUE}
a<-c(NBA1415$ThreesMade)
b<-c(NBA1415$ThreesAttempted)
NBA1415$ThreePointRate<-a/b
ThreePointer<-aggregate(ThreePointRate~Team,NBA1415,max)
NBA1415ThreePointer<-merge(NBA1415,ThreePointer)
output4<-NBA1415ThreePointer[order(NBA1415ThreePointer$ThreePointRate,decreasing = T)
,c("Team","Name","ThreePointRate")]
library(knitr)
kable(output4, digits=2)
```
