---
title: "1928-1969間，小兒麻痺在美國各州的發生率變化"
output: github_document
---

##資料前處理
```{r message=FALSE,warning=F,fig.height=4}
#讀csv資料
polio<-read.csv("POLIO_Incidence.csv",stringsAsFactors=F)
head(polio)
```


```{r message=FALSE,warning=F,fig.height=4}
#將寬表格轉為長表格,以年(YEAR)/週(WEEK)為基準,各州名column打散變長
library(reshape2)
polio.m<-melt(polio,id.vars=c('YEAR','WEEK'))
head(polio.m)
```

```{r message=FALSE,warning=F,fig.height=4}
#處理缺值,將"-"轉為NA
polio.m[polio.m$value=="-",]$value<-NA
#將value欄位轉為數字
polio.m$value<-as.numeric(polio.m$value)
#各州各年度加總,計算該年度的總發生率
polio.sumYear <-aggregate(value~YEAR+variable,data=polio.m,FUN=sum,na.rm=F)
head(polio.sumYear)
```


##視覺畫呈現

###解釋如何選擇圖形種類
由於要在一張圖裡呈現出美國各州1928-1969年間小兒麻痺發生率變化<br/>
因此我認為使用Heatmap將發生率的不同使用不同顏色做出漸層區隔，便能一目了然<br/>

```{r message=FALSE,warning=F}
#安裝並讀取ggplot2 package
if (!require('ggplot2'))
{install.packages("ggplot2");
  library(ggplot2) }

ggplot(polio.sumYear, aes(x=YEAR,y=variable)) + 
    geom_tile(aes(fill = value))+ 
    scale_fill_gradient(low = "yellow",high = "red") #數值低：黃色，數值高:紅色
```

###解釋圖形
1.整體而言，在1945-1955這10年間，美國各州小兒麻痺發生率有明顯的變化，又以1948年的SOUTH.DAKOTA(Value=151.86)和1954的Alaska(Value=154.98)顏色最紅最明顯<br/>
2.從各州的角度來看，每年的小兒麻痺發生率並沒有一個明確的規則變化(例:逐年增加，逐年減少等等)
